# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'info_manage.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(584, 525)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 60, 111, 41))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 120, 111, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(150, 60, 391, 101))
        self.tableWidget.setAutoScroll(False)
        self.tableWidget.setDragDropOverwriteMode(True)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setRowCount(1)
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.horizontalHeader().setMinimumSectionSize(42)
        self.tableWidget.verticalHeader().setDefaultSectionSize(50)
        self.tableWidget.verticalHeader().setMinimumSectionSize(30)
        self.group = QtWidgets.QLineEdit(self.centralwidget)
        self.group.setGeometry(QtCore.QRect(420, 20, 121, 31))
        self.group.setObjectName("group")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(340, 20, 91, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(130, 20, 91, 31))
        self.label_2.setObjectName("label_2")
        self.time_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.time_1.setGeometry(QtCore.QRect(210, 20, 121, 31))
        self.time_1.setObjectName("time_1")
        self.time_1.setPlaceholderText("eg：2020-01-01")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_2.setGeometry(QtCore.QRect(150, 270, 391, 101))
        self.tableWidget_2.setAutoScroll(False)
        self.tableWidget_2.setDragDropOverwriteMode(True)
        self.tableWidget_2.setShowGrid(True)
        self.tableWidget_2.setRowCount(1)
        self.tableWidget_2.setColumnCount(3)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.horizontalHeader().setMinimumSectionSize(42)
        self.tableWidget_2.verticalHeader().setDefaultSectionSize(50)
        self.tableWidget_2.verticalHeader().setMinimumSectionSize(30)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(340, 230, 91, 31))
        self.label_3.setObjectName("label_3")
        self.user_id = QtWidgets.QLineEdit(self.centralwidget)
        self.user_id.setGeometry(QtCore.QRect(420, 230, 121, 31))
        self.user_id.setObjectName("user_id")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(130, 230, 91, 31))
        self.label_4.setObjectName("label_4")
        self.time_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.time_2.setGeometry(QtCore.QRect(210, 230, 121, 31))
        self.time_2.setObjectName("time_2")
        self.time_2.setPlaceholderText("eg：2020-01-01")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(20, 300, 111, 41))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(430, 410, 111, 41))
        self.pushButton_4.setObjectName("pushButton_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 584, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "人脸信息删除"))
        self.pushButton_2.setText(_translate("MainWindow", "结果统计"))
        self.tableWidget.setSortingEnabled(False)
        self.label.setText(_translate("MainWindow", "   group："))
        self.label_2.setText(_translate("MainWindow", "   时间："))
        self.tableWidget_2.setSortingEnabled(False)
        self.label_3.setText(_translate("MainWindow", "     id："))
        self.label_4.setText(_translate("MainWindow", "   时间："))
        self.pushButton_3.setText(_translate("MainWindow", "结果修改"))
        self.pushButton_4.setText(_translate("MainWindow", "个人信息修改"))

